### ISSUE TITLE
Skins preview

### ISSUE THREAD

**Issue by bell07** [stujones11/multiskin#1]
At the first I did not tested the mod because of waiting for 0.4.16 is stable :-(
But I did a small code review to check if I can switch to multiskin in smart_inventory in next release.

I see 2 issues with multiskin.get_preview()
`local preview = get_player_skin(player).."_preview.png"`

1. The get_player_skin() returns a string that contain already ".png" suffix. So the generated preview string is not valid preview texture (character.png_preview.png). So a litle bit more string cutting is needed at this place
2. In case the skin is already handled by multiskin the player:get_attribute("multiskin_skin") should be preferred for preview determination, instead of "legacy" get_player_skin() result, like in on_joinplayer.

**Comment by stujones11** [comment]
Thanks, this is a bug I had not noticed, also using the attribute stored texture is likely better.
